# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0002_profile_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='location default text', max_length=120),
        ),
    ]
