# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0004_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='location default text', max_length=120, null=True),
        ),
    ]
