# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0006_auto_20181015_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
