# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0007_contactrecipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrecipient',
            old_name='name',
            new_name='fullname',
        ),
    ]
