# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0009_auto_20181016_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrecipient',
            name='comment',
            field=models.TextField(default=datetime.datetime(2018, 10, 16, 9, 42, 8, 684091, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
